development:
  adapter: postgresql
  database: profile_db
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: test_db
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: production_profile_db
  pool: 5
  timeout: 5000
